### ISSUE TITLE
Drag issue

### ISSUE THREAD

**Issue by mikemosseri** [papermerge/papermerge.js#45]
Whenever I try and drag an item in the UI, it throws errors. I am running with docker  papermerge/papermerge:2.1.9
This is in Chrome, Firefox, and Safari.

papermerge-99a900cb7e7fcd19b55df85749bd7142.js:783 Uncaught TypeError: Cannot read properties of undefined (reading 'positional')
    at i.onDragStart (papermerge-99a900cb7e7fcd19b55df85749bd7142.js:783:24)
onDragStart @ papermerge-99a900cb7e7fcd19b55df85749bd7142.js:783

papermerge-99a900cb7e7fcd19b55df85749bd7142.js:791 Uncaught TypeError: Cannot read properties of undefined (reading 'named')
    at n.onDragEnter (papermerge-99a900cb7e7fcd19b55df85749bd7142.js:791:94)
onDragEnter @ papermerge-99a900cb7e7fcd19b55df85749bd7142.js:791

papermerge-99a900cb7e7fcd19b55df85749bd7142.js:790 Uncaught TypeError: Cannot read properties of undefined (reading 'named')
    at n.onDragOver (papermerge-99a900cb7e7fcd19b55df85749bd7142.js:790:71)
onDragOver @ papermerge-99a900cb7e7fcd19b55df85749bd7142.js:790

Thank you.

**Comment by Lazyshot** [comment]
I am also having this issue. It would appear it was already being worked on here: https://github.com/papermerge/papermerge.js/tree/drag-and-drop-fix but no updates since August '22
